home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
   url(r'^$', views.index, name='index'),
   url(r'about/$', views.about, name='about'),
   url(r'contact/$', views.contact, name='contact'),
   url(r'mobile/$', views.mobile, name='mobile'),
   url(r'current-location-map-api/$', views.user_location_map, name='user_location_map'),
   url(r'near-by-map/$', views.nearby_event_map, name='nearby_event_map'),
   url(r'faq/$', views.faq, name='faq'),
   url(r'faq/available/$', views.faq_avail, name='faq_avail'),
   url(r'faq/compare/$', views.faq_compare, name='faq_compare'),
   url(r'faq/global-event/$', views.faq_global_event, name='faq_global_event'),
   url(r'faq/events/$', views.faq_events, name='faq_events'),
   url(r'set_user_location/$', views.set_user_location, name='set_user_location'),
   url(r'demo-video/lesson-101/$', views.demo_video, name='demo_video'),
   url(r'help/$', views.help, name='help'),
   url(r'help/available-artist/$', views.help_available_artist, name='help_available_artist'),
   url(r'help/compare-artist/$', views.help_compare_artist, name='help_compare_artist'),
   url(r'help/global-event/$', views.help_global_event, name='help_global_event'),
   url(r'help/create-event/$', views.help_create_event, name='help_create_event'),
   url(r'load-more-news/$', views.load_more_news, name='load_more_news'),
   url(r'privacy-policy/$', views.privacy_policy, name='privacy_policy'),
   url(r'terms/$', views.terms, name='terms'),
   url(r'^promoter/$', views.promoter_link, name='promoter_link'),
   url(r'^dj/$', views.dj_link, name='dj_link'),
   url(r'^agent/$', views.agent_link, name='agent_link'),

   ]

news/urls.py
from django.conf.urls import patterns, include, url

from news import views

urlpatterns = [
    url(r'^$', views.news, name='news'),
    url(r'^email-frequency/$', views.email_frequency, name='email_frequency'),
    url(r'^create-news/$', views.create_news, name='create_news'),
    url(r'^wdjp-news/$', views.wdjp_news, name='wdjp_news'),
    url(r'^news-detail/(?P<id>\d+)/$', views.news_detail, name="news_detail"),
    url(r'^wdjp-news/(?P<id>[0-9]+)/edit/$', views.news_edit, name='news_edit'),
    url(r'^wdjp-news/(?P<news_id>[0-9]+)$', views.delete_news, name='delete_news'),
    url(r'^search_news/$', views.search_news, name="search_news"),
    url(r'^my_news/$', views.my_news_feed, name="my_news_feed"),

]

pyadmin/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers

from artist.views import ArtistViewSet, GenreViewSet, source_list

router = routers.DefaultRouter()
router.register(r'genre', GenreViewSet)
router.register(r'artist', ArtistViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',  include('home.urls')),  # home page index
    url(r'^artists/', include('artist.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^sources/$', source_list),
    # url(r'^api/', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^events/', include('events.urls')),
    url(r'^availabilty-search/', include('dates.urls')),
    url(r'^territory/', include('geography.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^social-data/', include('social_data.urls')),
    url(r'', include('marketing_pages.urls')),
    url(r'^music-river/', include('music_river.urls')),
    url(r'^reports/', include('report.urls')),

    # url(r'^social_auth_login/([a-z]+)$',  social_auth_login, name='users-social-auth-login'),

    # url('', include('social.apps.django_app.urls', namespace='social')),
    # url('', include('django.contrib.auth.urls', namespace='auth')),

    url('', include('social_django.urls', namespace='social')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),
]

#handler404 = "accounts.views.custom_page_not_found"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS, show_indexes=True)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)


admin.site.site_header = 'Wheredjsplay Administration Board'

news/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

from accounts.models import Applications
from artist.models import Artist
from accounts.constants import NEWS_TYPES
from geography.models import Country, City

# Create your models here.
class NewsSource(models.Model):
    sourceName = models.CharField(max_length=50)
    sourceUrl = models.CharField(max_length=100)
    is_non_dance_website = models.BooleanField(default=False)

    def __str__(self):
        return u"{}".format(self.sourceName)


class News(models.Model):
    source = models.ForeignKey(NewsSource)
    imageurl = models.CharField(max_length=400, blank=True, null=True)
    url = models.CharField(max_length=300)
    title = models.CharField(max_length=500)
    text = models.TextField()
    modified_text = models.TextField(null=True, blank=True)
    publish_date = models.DateTimeField(null=True, blank=True)
    artists = models.ManyToManyField(Artist, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    country = models.ManyToManyField(Country, null=True, blank=True)

    def __str__(self):
        return u"{}-{}".format(self.url, self.source.sourceName)


class WdjpNews(models.Model):
    author = models.ForeignKey(User)
    published_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True)
    image = models.ImageField(upload_to='newsphotos/', blank=True, null=True)
    title = models.CharField(max_length=400, blank=True, null=True)
    text = RichTextField(verbose_name='text', null=True, blank=True)
    highlighted_text = models.CharField(max_length=400, blank=True, null=True)
    type = models.CharField(max_length=100, blank=True, null=True, choices=NEWS_TYPES)
    artists = models.ManyToManyField(Artist, related_name="artists",
                                                 null=True, blank=True)
    is_visible = models.BooleanField(default=True)
    news_for = models.ManyToManyField(Applications, null=True, blank=True)
    url = models.URLField(null=True, blank=True) 
    
    def __str__(self):
        return u"{}".format(self.title)

news/views.py
import json
import datetime
from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.conf import settings

from accounts.decorators import *
from geography.models import Country

from accounts.constants import NEWS_SOURCES
from news.models import NewsSource, News, WdjpNews
from artist.models import Artist, Genre
from news.forms import WdjpNewsForm, WdjpNewsImageForm
from accounts.models import Applications


@login_required
# @check_plan('Trial','Premium')
@check_plan('Trial','Promoter', 'Artist/DJ', 'Agent')
def news(request):
    limit = 10
    start = 0
    artist_name = request.GET.get('artist_name', '')
    query = request.GET.get('query', '')
    genre = request.GET.get('genre')
    country = request.GET.get('country')
    city = request.GET.get('city')

    if country:
        country_obj = Country.objects.filter(code=country)[0]

    profile_obj = Profile.objects.get(user=request.user)
    fav_artists = profile_obj.favorite_artist.all()
    email_frequency_value = profile_obj.email_frequency
    email_frequency_value_list = email_frequency_value.split(',')

    try:
        artist = Artist.objects.get(artistName=artist_name)
    except:
        artist = None
    all_news = News.objects.all().order_by('-publish_date')

    if genre:
        if genre == "edm":
            edm_genre = Genre.objects.get(genreName="EDM")
            edm_artist = Artist.objects.filter(genre=edm_genre)
            all_news = News.objects.filter(artists__in=edm_artist).order_by('-publish_date').distinct()

        if genre == "bass trap":
            bass_trap_genre = Genre.objects.get(genreName="Bass/Trap")
            bass_trap_artist = Artist.objects.filter(genre=bass_trap_genre)
            all_news = News.objects.filter(artists__in=bass_trap_artist).order_by('-publish_date').distinct()

        if genre == "Techno":
            techno_genre = Genre.objects.get(genreName="Techno")
            techno_artist = Artist.objects.filter(genre=techno_genre)
            all_news = News.objects.filter(artists__in=techno_artist).order_by('-publish_date').distinct()

        if genre == "Trance":
            trance_genre = Genre.objects.get(genreName="Trance")
            trance_artist = Artist.objects.filter(genre=trance_genre)
            all_news = News.objects.filter(artists__in=trance_artist).order_by('-publish_date').distinct()

        # if genre == "desert":
        #     desert_genre = Genre.objects.get(genreName="DESERT TRIBAL BEATS")
        #     desert_artist = Artist.objects.filter(genre=desert_genre)
        #     all_news = News.objects.filter(artists__in=desert_artist).order_by('-publish_date').distinct()

        # if genre == "edm":
        #     edm_genre = Genre.objects.get(genreName="EDM")
        #     edm_artist = Artist.objects.filter(genre=edm_genre)
        #     all_news = News.objects.filter(artists__in=edm_artist).order_by('-publish_date').distinct()[:15]

    if artist:
        all_news = all_news.filter(artists=artist)

    if query:
        all_news = all_news.filter(Q(title__icontains=query) | Q(text__icontains=query))

    # if country:
    #     all_news = all_news.filter(country=country_obj)
    #
    # if city:
    #     all_news = all_news.filter(Q(title__icontains=city) | Q(text__icontains=city))

    if request.is_ajax():
        start = request.GET.get('start', '')
        start = int(start)

        if all_news.count() > start + limit:
            more = True
        else:
            more = False


        all_news = all_news[start: start + limit]

        context = {
            'all_news': all_news,
        }
        template = render_to_string("news/load_more_news.html", context ,context_instance=RequestContext(request))

        response = {
            'data': template,
            'more': more,
            'start': start + limit,
        }

        return HttpResponse(json.dumps(response), content_type="application/json")

    countries = Country.objects.all()

    context = {
        'total_result': all_news.count(),
        'all_news': all_news[start:start + limit],
        'artist_name': artist_name,
        'start': start + limit,
        'query': query,
        'email_frequency_value': email_frequency_value,
        "email_frequency_value_list": email_frequency_value_list,
        'countries':countries,
        'city':city,
        'fav_artists':fav_artists
    }

    if country:
        context.update({"country_obj":country_obj})

    return render(request, 'news/all_news.html',context)


def email_frequency(request):
    profile_obj = Profile.objects.get(user=request.user)
    if request.method == "POST":
        email_frequency_choice = request.POST.getlist("email_frequency")
        if len(email_frequency_choice) >= 1 :
            if email_frequency_choice:
                profile_obj.email_frequency = ",".join(email_frequency_choice)
                profile_obj.save()
        else:
            profile_obj.email_frequency = " "
            profile_obj.save()

    # return redirect(reverse('news'))
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def create_news(request):
    if not request.user.is_superuser:
        return redirect("/")

    context = {}

    form = WdjpNewsForm(request.POST or None, request.FILES)

    image_form = WdjpNewsImageForm(request.POST or None, request.FILES)

    artists = Artist.objects.all().values_list('artistID', 'artistName')

    applications = Applications.objects.all().values_list('id', 'application_name')

    context.update({
        "form": form,
        "image_form": image_form,
        "artists": artists,
        "applications": applications
        })

    if request.method == "POST":

        if form.is_valid():
            is_visible = request.POST.get("is_visible")

            if is_visible == None:
                is_visible = False

            wdjp_news = WdjpNews.objects.create(
                title=form.cleaned_data["title"],
                text =form.cleaned_data["text"],
                highlighted_text=form.cleaned_data["highlighted_text"],
                type=form.cleaned_data["type"],
                is_visible=is_visible,
                author=request.user,
                url = form.cleaned_data["url"]
            )

            tag_artists_id = request.POST.getlist("tag_artists", " ")

            if tag_artists_id:
                tag_artists_id = [int(id) for id in tag_artists_id ]
                for id in tag_artists_id:
                    wdjp_news.artists.add(Artist.objects.get(artistID=id))


            tag_apps_id = request.POST.getlist("tag_apps", " ")

            if tag_apps_id:
                tag_apps_id = [int(id) for id in tag_apps_id ]
                for id in tag_apps_id:
                    wdjp_news.news_for.add(Applications.objects.get(id=id))


            if request.FILES:
                wdjp_news.image = request.FILES.get("image")

            wdjp_news.save()

            return redirect("wdjp_news")

    return render(request, "news/create_news.html", context)

# @login_required
# def create_news(request):
#     if not request.user.is_superuser:
#         return redirect("/")
#     context = {}

#     form = WdjpNewsForm(request.POST or None, request.FILES)

#     image_form = WdjpNewsImageForm(request.POST or None, request.FILES)

#     artists = Artist.objects.all().values_list('artistID', 'artistName')

#     applications =  Applications.objects.all().values_list('id', 'application_name')

#     context.update({
#         "form":form,
#         "image_form": image_form,
#         "artists": artists,
#         "applications": applications,

#     })

#     if request.method == "POST":

#         if form.is_valid():

# 			is_visible = request.POST.get("is_visible")

# 			if is_visible == None:
# 				is_visible = False

# 			wdjp_news = WdjpNews.objects.create(
# 				title = form.cleaned_data["title"],
# 				text=form.cleaned_data["text"],
# 				highlighted_text=form.cleaned_data["highlighted_text"],
# 				type=form.cleaned_data["type"],
# 				is_visible = is_visible,
# 				author=request.user
# 			)

#             tag_artists_id = request.POST.getlist("tag_apps", )


#             tag_apps_id =  request.POST.getlist("tag_apps", )

# 			if tag_artists_id:
# 				tag_artists_id = [int(id) for id in tag_artists_id]
# 				for id in tag_artists_id:
# 					wdjp_news.artists.add(Artist.objects.get(artistID=id))

# 			if request.FILES:
# 				wdjp_news.image = request.FILES.get("image")

# 			wdjp_news.save()
# 			return redirect("wdjp_news")

#     return render(request, "news/create_news.html", context)

@check_plan('Trial','Promoter', 'Artist/DJ', 'Agent')
def wdjp_news(request):
    context = {}

    application = Applications.objects.filter(application_name="WheredjsPlay").first()

    wdjp_news = WdjpNews.objects.filter(is_visible=True).order_by('-published_date')

    context.update({
        "wdjp_news": wdjp_news,
        "site_url": settings.SITE_URL,
    })

    return render(request, "news/wdjp_news.html", context)


def news_detail(request, id):
    context = {}
    limit = 21
    start = 0
    application = Applications.objects.filter(application_name="WheredjsPlay").first()

    wdjp_news_all = WdjpNews.objects.filter(news_for=application, is_visible=True).order_by('-published_date')
    wdjp_news_all = wdjp_news_all[start: start + limit]
    wdjp_news = WdjpNews.objects.get(id=id)
    tag_artists = wdjp_news.artists.all()

    context.update({
        "wdjp_news": wdjp_news,
        "wdjp_news_all":wdjp_news_all,
        "site_url": settings.SITE_URL,
        "tag_artists": tag_artists
    })

    return render(request, "news/news_detail.html", context)


@login_required

news/templates/news/_favorite_artists.html
{% load staticfiles %}
<div class="row">
    <div class="container">
        <div class="owl-carousel owl-theme">
            {% for sm_artist in fav_artists %}
                <div class="item">
                    <div class="wrapper">
                        {% if sm_artist.artistPhoto %}
                            <img src="{{ sm_artist.artistPhoto.url }}" alt="{{sm_artist.artistName}}" style="max-width:100px;width:100px;max-height:100px;height:100px">
                        {% else %}
                            <img src= "{% static 'frontend/images/team-member-1.jpg' %}" alt="{{sm_artist.artistName}}" style="max-width:100px;width:100px;max-height:100px;height:100px">
                        {% endif %}
                        <div style="margin-bottom:27px;">
                            <div class='description'>
                                <p class='description_content'><a style="color:white;text-decoration: none !important;" href="{% url 'artist_detail' sm_artist.artistID %}"><strong>{{sm_artist.artistName}}</strong></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

news/templates/news/news_edit.html
{% extends "home/__base.html" %}
{% load staticfiles %}
{% load artist_filters %}
{% load humanize %}
{% block title %} {{ block.super }} | Create News </title> {% endblock title %}
{% block header %}
 	{% include "home/_header.html" %}

	<style>
	#id_is_visible{
	display:block;
	margin-top: 30px;
	}
	</style>
{% endblock header %}

{% block extra_js %}

<script>
window.CKEDITOR_BASEPATH = '/static/ckeditor/'
</script>

<script type="text/javascript" src="{% static 'frontend/js/select2.min.js' %}"></script>
<link href="{% static 'frontend/css/select2.min.css' %}" rel="stylesheet">

<script type="text/javascript" src="{% static 'frontend/js/validator.js' %}"></script>


<script type="text/javascript">
    $(document).ready(function() {
			  $(".all_artists").select2();
    });
</script>


<script>
    $( "#id_image" ).keyup(function() {
        $("#image_error").text("");
    });
    $( "#id_title" ).keyup(function() {
        $("#title_error").text("");
    });
    $( "#id_highlighted_text" ).keyup(function() {
        $("#short_description_error").text("");
    });
    $( "#id_tag_artists" ).change(function() {
        $("#artist_error").text("");
    });
    $( "#id_type" ).change(function() {
        var type= $("id_type").val()
        if(type!=""){
            $("#type_error").text("");
        }
    });
    $("#id_tag_apps").change(function() {
        $("#app_error").text("");
    });
</script>


</script>

<script>

function form_validation(){
    var count = 0
    // var image = $("#id_image").val()
    var title = $("#id_title").val();
    var short_description = $("#id_highlighted_text").val()
    var type = $("#id_type").val()
    var tag_artists = $("#id_tag_artists").val()
    var tag_apps = $("#id_tag_apps").val()

    // if(image==""){
    //     $("#image_error").text("*This Field is required");
    //     count += 1
    // }

    if(title==""){
        $("#title_error").text("*This Field is required");
        count += 1
    }
    if(short_description==""){
        $("#short_description_error").text("*This Field is required");
        count += 1
    }
    if(type==""){
        $("#type_error").text("*This Field is required");
        count += 1
    }
    if(tag_artists==null){
        $("#artist_error").text("*This Field is required");
        count += 1
    }
    if(tag_apps == null){
        $("#app_error").text("*This Field is required");
        count += 1
    }
    else{
        if(count == 0){
            $("#news_form").submit()
        }
    }
}

$("#id_image").on('change', function () {
    var image_holder = $("#id_avatar_img");
    image_holder.empty();
    var reader = new FileReader();

    reader.onload = function (e) {
        $("<img/>", {
            "src": e.target.result,
            "style": 'height: 380px; width: 800px; cursor: pointer;'
        }).appendTo(image_holder);
    }

    $("#id_default_avatar").val("");
    image_holder.show();
    $("#image_error").hide();
    reader.readAsDataURL($(this)[0].files[0]);
});

$("#id_image").css("display", "none");

$("#id_avatar_img").on("click", function(){
    $("#id_image").click();
})

</script>

{% endblock %}


{% block slider%}
			<div class="breadcrumb-container">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-8">
                            <ol class="breadcrumb">
                                <li><i class="fa fa-home pr-10"></i><a href="index.html">Home</a></li>
        						<li class="active">Post News</li>
                            </ol>
                        </div>
                        <div class="hidden-sm hidden-md hidden-lg">
                            <div class="col-xs-2 col-xs-offset-2">
                                <ol class="breadcrumb">
                                    <span style="color:black" class="glyphicon glyphicon-chevron-left" onClick="javascript:history.go(-1);">Back</span>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
			</div>

{% endblock %}



{% block content %}
	<section class="main-container jumbotron light-gray-bg text-center margin-clear">
		<div class="container">
            <h2 style="text-align:center;"><strong>Post News Items</strong></h2>
            <h1 id="image_preview"></h1>
			<div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <form action="" method="POST" id="news_form" enctype="multipart/form-data" role="form" >
                        {% csrf_token %}

                        <label for="id_avatar_img"><strong class="pull-left">*Add Image for News :</strong><br/>
                        <small class="pull-left">We recommend keeping aspect ratio 2:1 (1024x512) and file size to less than 1MB</small>
                        </label>
                        <div id="id_avatar_img">
                            <img src="{{ site_url }}/media/{{news.image}}"
                                class="" class="img-circle" style="height: 380px; width: 800px; cursor: pointer;">
                        </div>
                            {{ form.image }}
                            <div class="pull-left">
                                <small class="help-block with-errors" id="image_error" style="color:red;"></small>
                            </div>

                        <br><br>

                        <div class="form-group">
                            <label for="id_title" class="pull-left"><strong>*What is the News Title :</strong></label>
                            {{ form.title }}
                            <div class="pull-left">
                                <small class="help-block with-errors" id="title_error" style="color:red;"></small>
                            </div>
                            <br>
                        </div>

                        <div class="form-group">
                            <label for="id_text"class="pull-left"><strong>*What is the Text Body :</strong></label><br><br>
                            <div id="div_id_text">
                                {{ form.text }}
                            </div>
                            <div class="pull-left">
                                <small class="help-block with-errors" id="text_error" style="color:red;"></small>
                            </div>
                        </div>

                            {{ form.media }}
                        <br>
                        <div class="form-group">
                            <label for="id_highlighted_text" class="pull-left"><strong>*What is the Short Description of News :</strong></label>
                            {{ form.highlighted_text }}
                            <div class="pull-left">
                                <small class="help-block with-errors" id="short_description_error" style="color:red;"></small>
                            </div>
                            <br>
                        </div>

                        <div class="form-group">
                            <label for="id_type" class="pull-left"><strong>*What Type of News it is :</strong></label>
                            <div>
                                {{ form.type }}

                            </div>
                            <div class="pull-left">
                                <small class="help-block with-errors" id="type_error" style="color:red;"></small>
                            </div>
                            <br>
                        </div>

                        <div class="form-group">
                            <label for="id_tag_artists" class="pull-left"><strong>*Tag the Artists For News :</strong></label>
                            <div>
                                <select name="tag_artists" class="form-control all_artists" multiple="multiple" id="id_tag_artists">
                                    {% for artist in artists %}
                                        <option value="{{artist.0}}" {% if artist in selected_artist %} selected {% endif %}> {{artist.1}} </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="pull-left">
                                <small class="help-block with-errors" id="artist_error" style="color:red;"></small>
                            </div>
                        </div>
                        <br>

                        <div class="form-group">
                            <label for="id_tag_apps" class="pull-left"><strong>*Applications For News :</strong></label>

                            <div>
                                <select name="tag_apps" class="form-control all_artists" multiple="multiple" id="id_tag_apps">
                                    {% for app in applications %}
                                        <option value="{{app.0}}" {% if app in selected_applications %} selected {% endif %}> {{app.1}} </option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="pull-left">
                                <small class="help-block with-errors" id="app_error" style="color:red;"></small>
                            </div>

                        </div>

                        <br>

                        <div class="form-group">
                            <label for="id_url" class="pull-left"><strong>Url:</strong></label>
                            {{ form.url }}
                            <div class="pull-left">
                                <small class="help-block with-errors" id="url_error" style="color:red;"></small>
                            </div>
                            <br>
                        </div>

						<div class="form-group">
								<label for="id_visible" class="pull-left" style="margin-right: 10px;margin-top: -5px;"><strong>*is_visible :</strong></label>
							<div>
								<input {% if news.is_visible == True %} checked="checked" {% endif %} id="id_is_visible" name="is_visible" type="checkbox">
							</div>
						</div>


        				<!-- <div class="form-group">
        					<label for="id_tag_artists" class="pull-left"><strong>*Is Visible :</strong></label>
                            <input type="checkbox" name="is_visible" value="Bike">I have a bike <br>
        				</div> -->

                        <a value="Create News" onclick="form_validation()" class="btn btn-default">Post News</a>
                    </form>
                </div>
			</div>
		</div>
	</section>

{% endblock content %}


{% block footer %}
	{% include "home/_footer.html" %}
{% endblock footer %}

news/templates/news/news_letter_mail.html
{% extends 'news/base_email.html' %}
{% load staticfiles %}
{% block email_body %}
    {% for news_obj in template_response %}
    {% if news_obj.news %}
        <tr>
            <td colspan="2">
                <hr> <h3 class="title" style="text-align:center">{{news_obj.artist.artistName}} News</h3> </hr>
            </td>
        </tr>
        <tr>
            <td class="innerpadding borderbottom">
                {% if news_obj.artist.artistPhoto %}
                    <a href="{{ site_url }}/artists/artist/{{ news_obj.artist.artistID }}">
                        <img src="{{ site_url }}{{ news_obj.artist.artistPhoto.url }}" alt="{{news_obj.artist.artistName}}" width="100%" height="350px" align="center">
                    </a>
                {% else %}
                   <a href="{{ site_url }}/artists/artist/{{ news_obj.artist.artistID }}">
                       <img src= "{{ site_url }}/static/frontend/images/team-member-1.jpg" alt="{{news_obj.artist.artistName}}"width="100%" height="350px" align="center">
                   </a>
                {% endif %}
            </td>
        </tr>
        {% if news_obj.news %}
                {% for news_article in news_obj.news %}
                    <tr>
                        <td class="innerpadding borderbottom h3">
                            <p>
                                <small style="text-transform: uppercase; font-weight: bold; letter-spacing: 1px; text-color: #000">{{ news_article.source }}</small>
                                <small style="text-transform: uppercase; font-weight: bold; letter-spacing: 1px; text-color: #000">{{ news_article.publish_date }}</small>
                            </p>
                            <h4>{{ news_article.title }}</h4>
                                {{ news_article.text|truncatewords:"40"|safe }}
                            <br/>
                            <br/>
                            <table class="buttonwrapper" align="center" bgcolor="#0c9ec7" border="0" cellspacing="0" cellpadding="0">
                              <tr>
                                <td class="button" height="45">
                                  <a href="{{news_article.url}}">Read article</a>
                                </td>
                              </tr>
                            </table>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        {% endif %}
        {% endfor %}
    <div class="buttonwrapper" bgcolor="#0c9ec7" align="center">
       <h4><a href="{{ site_url }}/profiles/edit-details/" >Email Frequency</a> | <a href="{{ site_url }}/artists/my-favourite/" >Favourite Artist</a></h4>
    </div>
{% endblock email_body %}