artist/urls.py
from django.conf.urls import url

from artist import views

urlpatterns = [
    url(r'^start_add_artist/$', views.start_add_artist, name="start_add_artist"),

    url(r'^artist_step_1_0/$', views.artist_step_1_0, name="artist_step_1_0"),
    url(r'^artist_step_1_1/$', views.artist_step_1_1, name="artist_step_1_1"),
    url(r'^artist_step_1/$', views.artist_step_1, name="artist_step_1"),
    url(r'^validate-artist-name/$', views.validate_artist_name, name='validate_artist_name'),
    
    url(r'^artist_step_2_edit/(?P<artist_id>\d+)$', views.artist_step_2_edit, name="artist_step_2_edit"),
    url(r'^artist_step_2/$', views.artist_step_2, name="artist_step_2"),

    url(r'^artist_step_3_16/(?P<artist_id>\d+)$', views.artist_step_3_16, name="artist_step_3_16"),
    url(r'^artist_step_3_1/(?P<artist_id>\d+)$', views.artist_step_3_1, name="artist_step_3_1"),
    url(r'^artist_step_3_2/(?P<artist_id>\d+)$', views.artist_step_3_2, name="artist_step_3_2"),
    url(r'^artist_step_3_3/(?P<artist_id>\d+)$', views.artist_step_3_3, name="artist_step_3_3"),
    url(r'^artist_step_3_4/(?P<artist_id>\d+)$', views.artist_step_3_4, name="artist_step_3_4"),
    url(r'^artist_step_3_5/(?P<artist_id>\d+)$', views.artist_step_3_5, name="artist_step_3_5"),
    url(r'^artist_step_3_6/(?P<artist_id>\d+)$', views.artist_step_3_6, name="artist_step_3_6"),
    url(r'^artist_step_3_7/(?P<artist_id>\d+)$', views.artist_step_3_7, name="artist_step_3_7"),
    url(r'^artist_step_3_8/(?P<artist_id>\d+)$', views.artist_step_3_8, name="artist_step_3_8"),
    url(r'^artist_step_3_9/(?P<artist_id>\d+)$', views.artist_step_3_9, name="artist_step_3_9"),
    url(r'^artist_step_3_10/(?P<artist_id>\d+)$', views.artist_step_3_10, name="artist_step_3_10"),
    url(r'^artist_step_3_11/(?P<artist_id>\d+)$', views.artist_step_3_11, name="artist_step_3_11"),
    url(r'^artist_step_3_12/(?P<artist_id>\d+)$', views.artist_step_3_12, name="artist_step_3_12"),
    url(r'^artist_step_3_13/(?P<artist_id>\d+)$', views.artist_step_3_13, name="artist_step_3_13"),
    url(r'^artist_step_3_14/(?P<artist_id>\d+)$', views.artist_step_3_14, name="artist_step_3_14"),
    url(r'^artist_step_3_15/(?P<artist_id>\d+)$', views.artist_step_3_15, name="artist_step_3_15"),

    url(r'^artist_step_4/(?P<artist_id>\d+)$', views.artist_step_4, name="artist_step_4"),

    url(r'^artist_step_5/(?P<artist_id>\d+)$', views.artist_step_5, name="artist_step_5"),
    url(r'^artist_step_5_confirm/(?P<artist_id>\d+)$', views.artist_step_5_confirm, name="artist_step_5_confirm"),

    url(r'^artist_step_profile/(?P<artist_id>\d+)$', views.artist_step_profile, name="artist_step_profile"),

    url(r'^artist_step_similar_artists/(?P<artist_id>\d+)$', views.artist_step_similar_artists, name="artist_step_similar_artists"),

    url(r'^artist_step_6_preview/(?P<artist_id>\d+)$', views.artist_step_6_preview, name="artist_step_6_preview"),
    url(r'^artist_step_6/(?P<artist_id>\d+)$', views.artist_step_6, name="artist_step_6"),
    
    url(r'^artist_submit_details/(?P<artist_id>\d+)$', views.artist_submit_details, name="artist_submit_details"),

    url(r'^new-artist-to-complete/$', views.new_artist_to_complete, name='new_artist_to_complete'),

    url(r'^artist/(?P<artist_id>\d+)/$', views.artist_detail, name='artist_detail'),
    url(r'^artist/(?P<artist_id>\d+)/load_events/$', views.load_events, name='load_events'),
    url(r'^artist/add-or-remove-favorite/$', views.add_or_remove_favorite, name='add_or_remove_favorite'),
    url(r'^artist/add-or-remove-shortlist/$', views.add_or_remove_shortlist, name='add_or_remove_shortlist'),
    url(r'^artist_map/(?P<artist_id>\d+)/$', views.artist_map_frame, name='artist_map_frame'),
    url(r'^maps/$', views.artist_map, name="artist_map"),
    url(r'^search/$', views.artist_search, name="artist_search"),
    url(r'^load-search-artist/$', views.load_search_artist, name="load_search_artist"),
    url(r'^master-search/$', views.master_search, name="master_search"),
    # url(r'^detail-mobile/$', views.detail_mobile, name="detail_mobile"),
    url(r'^music-you-love/$', views.someone_music_you_love, name="someone_music_you_love"),
    url(r'filter-name/$', views.filter_artist_name, name="filter_artist_name"),
    url(r'filter-artist/$', views.filter_name_artist, name="filter_name_artist"),
    url(r'filter-city/$', views.filter_name_city, name="filter_name_city"),
    url(r'filter-all/$', views.filter_all, name="filter_all"),
    url(r'filter-all-art/$', views.filter_all_art, name="filter_all_art"),

    url(r'^flight-share/$', views.flight_share, name="flight_share"),
    url(r'^email-listings/(?P<artist_id>\d+)/$', views.email_listings, name="email_listings"),
    url(r'^free-dates/(?P<artist_id>\d+)/$', views.free_dates, name="free_dates"),
    url(r'^email-artists/$', views.email_artist, name="email_artist"),
    url(r'^my-favourite/$', views.favorite, name="favorite"),
    url(r'^compare_dj/$', views.artist_compare_dj, name="artist_compare_dj"),
    url(r'^compare/$', views.compare_artists, name="compare_artists"),
    url(r'^filter-all-submit/$', views.filter_all_submit, name="filter_all_submit"),
    url(r'^filter-artist-report/$', views.filter_artist_report, name="filter_artist_report"),
    url(r'^$', views.artists, name='artists'),
    # url(r'^find-similar/(?P<artist_name>.*)/$', views.find_similar, name='find_similar'),
    url(r'^find-similar/$', views.find_similar, name='find_similar'),
    url(r'^artist-exist-or-not/$', views.artist_exist_or_not, name='artist_exist_or_not'),
    url(r'^get-data/$', views.get_data, name='get_data'),
    # url(r'^dj-artist/$', views.dj_artist, name='dj_artist'),
    url(r'^edit-artist-detail/$', views.edit_artist_detail, name='edit_artist_detail'),
    url(r'^add-djartist-1/$', views.add_djartist_1, name='add_djartist_1'),
    url(r'^add-djartist-2/$', views.add_djartist_2, name='add_djartist_2'),
    url(r'^add-djartist-3/$', views.add_djartist_3, name='add_djartist_3'),
    url(r'^add-djartist-4/$', views.add_djartist_4, name='add_djartist_4'),
    url(r'^add-djartist-5/(?P<artist_id>\d+)/$', views.add_djartist_5, name='add_djartist_5'),
    url(r'^add-artist-5/(?P<artist_id>\d+)/$', views.add_artist_5, name='add_artist_5'),

    url(r'^edit-djartist-1/(?P<artist_id>\d+)/$', views.edit_djartist_1, name='edit_djartist_1'),
    url(r'^edit-djartist-2/(?P<artist_id>\d+)/$', views.edit_djartist_2, name='edit_djartist_2'),
    url(r'^edit-djartist-3/(?P<artist_id>\d+)/$', views.edit_djartist_3, name='edit_djartist_3'),
    url(r'^edit-djartist-4/(?P<artist_id>\d+)/$', views.edit_djartist_4, name='edit_djartist_4'),

    url(r'^add-managed-djs/$', views.add_managed_djs, name="add_managed_djs"),
    url(r'^add-added-djs/$', views.add_added_djs, name="add_added_djs"),

    url(r'^edit-added-artist-1/(?P<artist_id>\d+)/$', views.edit_added_artist_1, name='edit_added_artist_1'),
    url(r'^edit-added-artist-2/(?P<artist_id>\d+)/$', views.edit_added_artist_2, name='edit_added_artist_2'),
    url(r'^edit-added-artist-3/(?P<artist_id>\d+)/$', views.edit_added_artist_3, name='edit_added_artist_3'),
    url(r'^edit-added-artist-4/(?P<artist_id>\d+)/$', views.edit_added_artist_4, name='edit_added_artist_4'),

    url(r'^get-artist-data/$', views.get_artist_data, name="get_artist_data"),
    url(r'^admin-approve/(?P<artist_id>\d+)/$', views.admin_approve, name='admin_approve'),
    url(r'^email/$', views.logo, name='logo'),
    url(r'^social-data-xls/$', views.social_data_xls, name='social_data_xls'),

    url(r'trends', views.trending_top, name='trends'),
    url(r'user_note/(?P<note_id>\d+)/$', views.user_note, name='user_note'),
    url(r'delete_note/(?P<note_id>\d+)/$', views.delete_note, name='delete_note'),
    url(r'user_comment/(?P<artist_id>\d+)/$', views.user_comment, name='user_comment'),
    url(r'delete_comment/(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),

    url(r'^save_artist_info/(?P<artist_id>\d+)/$', views.save_artist_info, name="save_artist_info"),
    url(r'^delete-artist-file/(?P<artist_id>\d+)/$', views.delete_artist_file, name="delete_artist_file"),
    url(r'^save_artist_creative_info/(?P<artist_id>\d+)/$', views.save_creative_artist_info, name="save_artist_creative_info"),
    
    url(r'^artist/(?P<artist_id>\d+)/load_shortlist_venues/$', views.load_shortlist_venues, name='load_shortlist_venues'),
    url(r'^artist/(?P<artist_id>\d+)/load_shortlist_events/$', views.load_shortlist_events, name='load_shortlist_events'),

    # Getting all events for particular artist
    url(r'^get-artist-events-json/$', views.get_artist_events_json, name='get_artist_events_json'),

    # All artists notes
    url(r'^notes/$', views.artists_notes, name='artists_notes'),

    # Artist Promo Urls
    url(r'^save_artist_photos/(?P<artist_id>\d+)/$', views.save_artist_photos, name="save_artist_photos"),
    url(r'^save_artist_media/(?P<artist_id>\d+)/$', views.save_artist_media, name="save_artist_media"),
    url(r'^artist_media_delete/(?P<media_id>\d+)/(?P<artist_id>\d+)$', views.artist_media_delete, name="artist_media_delete"),
    url(r'^artist_photo_delete/(?P<photo_id>\d+)/(?P<artist_id>\d+)$', views.artist_photo_delete, name="artist_photo_delete"),

    # Mail Views
    url(r'^email-travel-docs/(?P<artist_id>\d+)/$', views.email_travel_docs, name="email_travel_docs"),

    url(r'^search-all-artists/$', views.search_all_artists, name="search_all_artists"),

    # Offersheet
    url(r'^create-offersheet/$', views.create_artist_offersheet, name="create_artist_offersheet"),
    url(r'^offersheet-more-options/(?P<artist_id>\d+)/$', views.offersheet_final_step, name="offersheet_final_step"),
    url(r'^offersheet-created/(?P<artist_id>\d+)/$', views.offersheet_created, name="offersheet_created"),
    url(r'^offersheet/(?P<artist_id>\d+)/edit/$', views.edit_offersheet, name="edit_offersheet"),

    # Offer creation
    url(r'^offersheet/(?P<artist_id>\d+)/$', views.create_offer, name="offer"),

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
   url(r'^$', views.index, name='index'),
   url(r'about/$', views.about, name='about'),
   url(r'contact/$', views.contact, name='contact'),
   url(r'mobile/$', views.mobile, name='mobile'),
   url(r'current-location-map-api/$', views.user_location_map, name='user_location_map'),
   url(r'near-by-map/$', views.nearby_event_map, name='nearby_event_map'),
   url(r'faq/$', views.faq, name='faq'),
   url(r'faq/available/$', views.faq_avail, name='faq_avail'),
   url(r'faq/compare/$', views.faq_compare, name='faq_compare'),
   url(r'faq/global-event/$', views.faq_global_event, name='faq_global_event'),
   url(r'faq/events/$', views.faq_events, name='faq_events'),
   url(r'set_user_location/$', views.set_user_location, name='set_user_location'),
   url(r'demo-video/lesson-101/$', views.demo_video, name='demo_video'),
   url(r'help/$', views.help, name='help'),
   url(r'help/available-artist/$', views.help_available_artist, name='help_available_artist'),
   url(r'help/compare-artist/$', views.help_compare_artist, name='help_compare_artist'),
   url(r'help/global-event/$', views.help_global_event, name='help_global_event'),
   url(r'help/create-event/$', views.help_create_event, name='help_create_event'),
   url(r'load-more-news/$', views.load_more_news, name='load_more_news'),
   url(r'privacy-policy/$', views.privacy_policy, name='privacy_policy'),
   url(r'terms/$', views.terms, name='terms'),
   url(r'^promoter/$', views.promoter_link, name='promoter_link'),
   url(r'^dj/$', views.dj_link, name='dj_link'),
   url(r'^agent/$', views.agent_link, name='agent_link'),

   ]

pyadmin/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers

from artist.views import ArtistViewSet, GenreViewSet, source_list

router = routers.DefaultRouter()
router.register(r'genre', GenreViewSet)
router.register(r'artist', ArtistViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',  include('home.urls')),  # home page index
    url(r'^artists/', include('artist.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^sources/$', source_list),
    # url(r'^api/', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^events/', include('events.urls')),
    url(r'^availabilty-search/', include('dates.urls')),
    url(r'^territory/', include('geography.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^social-data/', include('social_data.urls')),
    url(r'', include('marketing_pages.urls')),
    url(r'^music-river/', include('music_river.urls')),
    url(r'^reports/', include('report.urls')),

    # url(r'^social_auth_login/([a-z]+)$',  social_auth_login, name='users-social-auth-login'),

    # url('', include('social.apps.django_app.urls', namespace='social')),
    # url('', include('django.contrib.auth.urls', namespace='auth')),

    url('', include('social_django.urls', namespace='social')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),
]

#handler404 = "accounts.views.custom_page_not_found"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS, show_indexes=True)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)


admin.site.site_header = 'Wheredjsplay Administration Board'

news/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

from accounts.models import Applications
from artist.models import Artist
from accounts.constants import NEWS_TYPES
from geography.models import Country, City

# Create your models here.
class NewsSource(models.Model):
    sourceName = models.CharField(max_length=50)
    sourceUrl = models.CharField(max_length=100)
    is_non_dance_website = models.BooleanField(default=False)

    def __str__(self):
        return u"{}".format(self.sourceName)


class News(models.Model):
    source = models.ForeignKey(NewsSource)
    imageurl = models.CharField(max_length=400, blank=True, null=True)
    url = models.CharField(max_length=300)
    title = models.CharField(max_length=500)
    text = models.TextField()
    modified_text = models.TextField(null=True, blank=True)
    publish_date = models.DateTimeField(null=True, blank=True)
    artists = models.ManyToManyField(Artist, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    country = models.ManyToManyField(Country, null=True, blank=True)

    def __str__(self):
        return u"{}-{}".format(self.url, self.source.sourceName)


class WdjpNews(models.Model):
    author = models.ForeignKey(User)
    published_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True)
    image = models.ImageField(upload_to='newsphotos/', blank=True, null=True)
    title = models.CharField(max_length=400, blank=True, null=True)
    text = RichTextField(verbose_name='text', null=True, blank=True)
    highlighted_text = models.CharField(max_length=400, blank=True, null=True)
    type = models.CharField(max_length=100, blank=True, null=True, choices=NEWS_TYPES)
    artists = models.ManyToManyField(Artist, related_name="artists",
                                                 null=True, blank=True)
    is_visible = models.BooleanField(default=True)
    news_for = models.ManyToManyField(Applications, null=True, blank=True)
    url = models.URLField(null=True, blank=True) 
    
    def __str__(self):
        return u"{}".format(self.title)

artist/templates/artist/offerhq/offerhq.html
{% extends "home/__base.html" %}
{% load staticfiles %}
{% load event_filters %}
{% load artist_filters %}
{% load humanize %}
{% block title %} {{ block.super }} | {{artist.artistName}} Offersheet </title> {% endblock title %}

{% block header %}
    {% include "home/_header.html" %}
{% endblock header %}

{% block extra_js %}
<script>
    $("#new_offersheet").click(function() {
        $("#artist_select").modal("show");
    })

    $("#id_artists").change(function() {
        var artist = $(this).val();
        if(artist==""){
            $("#create_offersheet_btn").addClass("disabled")
        }else{
            var url = "{% url 'create_artist_offersheet' %}?artistID="+artist;
            $("#create_offersheet_btn").removeClass("disabled")
            $("#hidden_artist_id").val(artist)
            $("#offersheet_form").attr("action", url)
        }
    });
</script>
{% endblock %}

{% block content %}
    <h1 class="text-center" style="margin-top: 50px;">Offers HQ</h1>

    <div class="container" style="margin-top: 75px;margin-bottom: 100px">
        <ul class="nav nav-tabs">
            <li class="active">
                <a data-toggle="tab" href="#offersheet">Offersheets
                    <span class="badge">{{offersheets_count}}</span>
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#streams">Streams
                    <span class="badge">{{streams_count}}</span>
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#virtual_events">Virtual Events
                    <span class="badge">{{virtual_events_count}}</span>
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#live">Live
                    <span class="badge">{{live_events_count}}</span>
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#studio">Studio
                    <span class="badge">{{interview_count}}</span>
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#lessons">Lessons
                    <span class="badge">{{private_music_count}}</span>
                </a>
            </li>
        </ul>

        <div class="tab-content" style="margin-top:20px;">
            <div id="offersheet" class="tab-pane fade in padding_none active">
                {% if offersheets %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Artist Name</th>
                                <th>Streams</th>
                                <th>Live Events</th>
                                <th>Virtual Events</th>
                                <th>Teach / Share</th>
                                <th>Press/Promo</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for offersheet in offersheets %}
                                <tr>
                                    <th>
                                        {{offersheet.artist.artistName}}
                                    </th>
                                    <th>{% if offersheet.stream %}Yes{% else %}No{% endif %}</th>
                                    <th>{% if offersheet.live_events %}Yes{% else %}No{% endif %}</th>
                                    <th>{% if offersheet.virtual_events %}Yes{% else %}No{% endif %}</th>
                                    <th>{% if offersheet.private_music %}Yes{% else %}No{% endif %}</th>
                                    <th>{% if offersheet.interview %}Yes{% else %}No{% endif %}</th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="text-center">Sorry You haven't create any offersheet yet!</p>
                {% endif %}

                <div class="text-center" style="margin-top: 50px;">
                    <a href="#" class="btn btn-success" id="new_offersheet">Create New Offersheet</a>
                </div>
            </div>
            <div id="streams" class="tab-pane fade in padding_none">
                {% if streams %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Request Name</th>
                                <th>Artist Name</th>
                                <th>By</th>
                                <th>Date</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for offer in streams %}
                                <tr>
                                    <th><a href="{% url 'view_offer' offer.id %}">{{offer.request_name}}</a></th>
                                    <th>{{offer.artist.artistName}}</th>
                                    <th>{{offer.name}}</th>
                                    <th>{{offer.date}}</th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="text-center">Sorry there are no stream offers yet.</p>
                {% endif %}
            </div>
            <div id="virtual_events" class="tab-pane fade in padding_none">
                {% if virtual_events %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Request Name</th>
                                <th>Artist Name</th>
                                <th>By</th>
                                <th>Date</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for offer in virtual_events %}
                                <tr>
                                    <th><a href="{% url 'view_offer' offer.id %}">{{offer.request_name}}</a></th>
                                    <th>{{offer.artist.artistName}}</th>
                                    <th>{{offer.name}}</th>
                                    <th>{{offer.date}}</th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="text-center">Sorry there are no virtual event offers yet.</p>
                {% endif %}
            </div>
            <div id="live" class="tab-pane fade in padding_none">
                {% if live_events %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Request Name</th>
                                <th>Artist Name</th>
                                <th>By</th>
                                <th>Date</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for offer in live_events %}
                                <tr>
                                    <th><a href="{% url 'view_offer' offer.id %}">{{offer.request_name}}</a></th>
                                    <th>{{offer.artist.artistName}}</th>
                                    <th>{{offer.name}}</th>
                                    <th>{{offer.date}}</th>
                                    {% if offer.status == 0 %}
                                        <th>New</th>
                                    {% endif %}
                                    {% if offer.status == 1 %}
                                        <th>Hold</th>
                                    {% endif %}
                                    {% if offer.status == 2 %}
                                        <th>Accepted</th>
                                    {% endif %}
                                    {% if offer.status == 3 %}
                                        <th>Rejected</th>
                                    {% endif %}

                                    <th><a class="btn btn-primary btn-sm"  href="{% url 'view_offer' offer.id %}"  style="width: 120px;">View Offer</a></th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="text-center">Sorry there are no live event offers yet.</p>
                {% endif %}
            </div>
            <div id="studio" class="tab-pane fade in padding_none">
                {% if interview %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Request Name</th>
                                <th>Artist Name</th>
                                <th>By</th>
                                <th>Date</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for offer in interview %}
                                <tr>
                                    <th><a href="{% url 'view_offer' offer.id %}">{{offer.request_name}}</a></th>
                                    <th>{{offer.artist.artistName}}</th>
                                    <th>{{offer.name}}</th>
                                    <th>{{offer.date}}</th>
                                    {% if offer.status == 0 %}
                                        <th>New</th>
                                    {% endif %}
                                    {% if offer.status == 1 %}
                                        <th>Hold</th>
                                    {% endif %}
                                    {% if offer.status == 2 %}
                                        <th>Accepted</th>
                                    {% endif %}
                                    {% if offer.status == 3 %}
                                        <th>Rejected</th>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="text-center">Sorry there are no studio offers yet.</p>
                {% endif %}
            </div>
            <div id="lessons" class="tab-pane fade in padding_none">
                {% if private_music %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Request Name</th>
                                <th>Artist Name</th>
                                <th>By</th>
                                <th>Date</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for offer in private_music %}
                                <tr>
                                    <th><a href="{% url 'view_offer' offer.id %}">{{offer.request_name}}</a></th>
                                    <th>{{offer.artist.artistName}}</th>
                                    <th>{{offer.name}}</th>
                                    <th>{{offer.date}}</th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="text-center">Sorry there are no stream offers yet.</p>
                {% endif %}
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" tabindex="-1" role="dialog" id="artist_select">
      <div class="modal-dialog credit_card_payment" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Offersheet Creation</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            
            <div class="modal-body" style="padding: 30px 20px;">
                
                <div class="form-group">
                    <label class="py-label" for="id_artists">Select the artist for which you want to make offersheet:</label><br>
                    <select class="py-form-control" id="id_artists">
                        <option value="" selected="selected">---------</option>
                        {% for no_offersheet_artist in no_offersheet_artists %}
                            <option value="{{no_offersheet_artist.artistID}}">{{no_offersheet_artist.artistName}}</option>
                        {% endfor %}
                    </select>
                    <p class="error"></p>
                </div>

                <form action="" method="post" id="offersheet_form">
                    {% csrf_token %}
                    <input type="hidden" value="" name="artistID" id="hidden_artist_id"/>
                    <button type="submit" class="btn btn-success disabled" id="create_offersheet_btn">Create {{ artist.artistName }} Offersheet</button>
                </form>
            </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block footer %}
	{% include "home/_footer.html" %}
{% endblock footer %}